/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema_vacantes_java.recluador;

import com.mycompany.sistema_vacantes_java.inicio.inicio;
import com.mycompany.sistema_vacantes_java.conexion.ConexionBD;
import com.mycompany.sistema_vacantes_java.conexion.Sesion;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;

/**
 *
 * @author Yaelita
 */
public class LoginReclut extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginReclut.class.getName());

    /**
     * Creates new form LoginReclut
     */
    
    
    
    
    public LoginReclut() {
        initComponents();
         this.pack();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BienvenidoLabel = new javax.swing.JLabel();
        RecluadorLabel = new javax.swing.JLabel();
        CorreoELabel = new javax.swing.JLabel();
        CorreoETextField = new javax.swing.JTextField();
        ContrasenaLabel = new javax.swing.JLabel();
        ContrasenaPasswordField = new javax.swing.JPasswordField();
        IniciarSesionButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 153, 255));

        BienvenidoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        BienvenidoLabel.setText("Bienvenido ");

        RecluadorLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        RecluadorLabel.setForeground(new java.awt.Color(102, 0, 102));
        RecluadorLabel.setText("Reclutador");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(BienvenidoLabel)
                .addGap(38, 38, 38))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(RecluadorLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(BienvenidoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RecluadorLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        CorreoELabel.setText("Correo electronico:");

        ContrasenaLabel.setText("contraseña:");

        IniciarSesionButton.setBackground(new java.awt.Color(204, 0, 204));
        IniciarSesionButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IniciarSesionButton.setForeground(new java.awt.Color(255, 255, 255));
        IniciarSesionButton.setText("Iniciar Sesión");
        IniciarSesionButton.addActionListener(this::IniciarSesionButtonActionPerformed);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 153));
        jButton1.setText("REGRESAR");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CorreoELabel)
                                    .addComponent(CorreoETextField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ContrasenaLabel)
                                    .addComponent(ContrasenaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(80, 80, 80)
                                .addComponent(IniciarSesionButton)))
                        .addGap(0, 57, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(16, 16, 16))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(CorreoELabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CorreoETextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ContrasenaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ContrasenaPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(IniciarSesionButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IniciarSesionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniciarSesionButtonActionPerformed
      try {
    String correo = CorreoETextField.getText().trim();
    String password = "";
    
    char[] passwordChars = ContrasenaPasswordField.getPassword();
    password = new String(passwordChars);
    
    if (correo.isEmpty() || password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(null, "Por favor, ingresa tu correo y contraseña.", "Campos vacíos", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    Connection con = ConexionBD.conectar();
    String sql = "SELECT id, nombre, correo, estado FROM reclutadores WHERE correo = ? AND contrasena = ?";
    PreparedStatement ps = con.prepareStatement(sql);
    ps.setString(1, correo);
    ps.setString(2, password);
    ResultSet rs = ps.executeQuery();

    if (rs.next()) {
        if ("Inactivo".equalsIgnoreCase(rs.getString("estado"))) {
            javax.swing.JOptionPane.showMessageDialog(null, "Esta cuenta de reclutador está inactiva.", "Cuenta inactiva", javax.swing.JOptionPane.WARNING_MESSAGE);
        } else {
            Sesion.reclutadorId = rs.getInt("id");
            Sesion.reclutadorNombre = rs.getString("nombre");
            Sesion.reclutadorCorreo = rs.getString("correo");

            rs.close();
            ps.close();
            con.close();

            com.mycompany.sistema_vacantes_java.recluador.InicioReclutador ventana =
                    new com.mycompany.sistema_vacantes_java.recluador.InicioReclutador();
            ventana.setVisible(true);
            this.dispose();
            return;
        }
    } else {
        javax.swing.JOptionPane.showMessageDialog(null, "Correo o contraseña incorrectos.", "Error de Autenticación", javax.swing.JOptionPane.ERROR_MESSAGE);
        ContrasenaPasswordField.setText("");
    }

    rs.close();
    ps.close();
    con.close();
    
} catch (Exception ex) {
    javax.swing.JOptionPane.showMessageDialog(null, "Ocurrió un error: " + ex.getMessage());
}
    }//GEN-LAST:event_IniciarSesionButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false); 
        inicio inicio = new inicio();
    inicio.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginReclut().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BienvenidoLabel;
    private javax.swing.JLabel ContrasenaLabel;
    private javax.swing.JPasswordField ContrasenaPasswordField;
    private javax.swing.JLabel CorreoELabel;
    private javax.swing.JTextField CorreoETextField;
    private javax.swing.JButton IniciarSesionButton;
    private javax.swing.JLabel RecluadorLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
