/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema_vacantes_java.administrador;

import com.mycompany.sistema_vacantes_java.conexion.ConexionBD;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Yaelita
 */
public class AdminAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminAdmin.class.getName());

    /**
     * Creates new form AdminAdmin
     */
    public AdminAdmin() {
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
        cargarAdministradores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AgregarButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAdmin = new javax.swing.JTable();
        RegresaeButton = new javax.swing.JButton();
        EliminarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 255)));

        jLabel1.setText("Administrador");

        AgregarButton.setBackground(new java.awt.Color(153, 153, 255));
        AgregarButton.setText("+ Agregar Administrador");
        AgregarButton.addActionListener(this::AgregarButtonActionPerformed);

        TableAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TableAdmin);

        RegresaeButton.setBackground(new java.awt.Color(153, 153, 255));
        RegresaeButton.setText("Regresar");
        RegresaeButton.addActionListener(this::RegresaeButtonActionPerformed);

        EliminarButton.setBackground(new java.awt.Color(153, 153, 255));
        EliminarButton.setText("Eliminar Administrador");
        EliminarButton.addActionListener(this::EliminarButtonActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AgregarButton)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(EliminarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RegresaeButton)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AgregarButton)
                    .addComponent(jLabel1))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegresaeButton)
                    .addComponent(EliminarButton))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarButtonActionPerformed
        this.setVisible(false);
        AgregarAdmin ventana = new AgregarAdmin();
      ventana.setVisible(true);
      this.dispose();
    }//GEN-LAST:event_AgregarButtonActionPerformed

    private void RegresaeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresaeButtonActionPerformed
        this.setVisible(false);
    InicioAdmin inicio = new InicioAdmin();

    inicio.setVisible(true);
    this.dispose();
        
    }//GEN-LAST:event_RegresaeButtonActionPerformed

    private void EliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarButtonActionPerformed
     
    int filaSeleccionada = TableAdmin.getSelectedRow();
    
    if (filaSeleccionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecciona un administrador a eliminar");
        return;
    }
    
    int confirmar = javax.swing.JOptionPane.showConfirmDialog(
        this, 
        "¿Estás seguro de que deseas eliminar este administrador?", 
        "Confirmar Eliminación", 
        javax.swing.JOptionPane.YES_NO_OPTION
    );
    
    if (confirmar == javax.swing.JOptionPane.YES_OPTION) {
        int idEliminar = (int) TableAdmin.getValueAt(filaSeleccionada, 0);
        
        try {
            Connection con = ConexionBD.conectar();
            String sql = "DELETE FROM administradores WHERE id = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setInt(1, idEliminar);
            
            int resultado = ps.executeUpdate();
            
            if (resultado > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Administrador eliminado correctamente.");
                cargarAdministradores(); 
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "No se pudo eliminar el registro.");
            }
            
            ps.close(); 
            con.close();
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage());
            System.out.println(e.getMessage());
        }
    }

    }//GEN-LAST:event_EliminarButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    private void cargarAdministradores() {
    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("ID");
    modelo.addColumn("Nombre");
    modelo.addColumn("Correo");
    modelo.addColumn("Estado");
    try {
        Connection con = ConexionBD.conectar();
        String sql = "SELECT id, nombre, correo, estado FROM administradores";
        PreparedStatement ps = con.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            Object fila[] = { rs.getInt("id"), rs.getString("nombre"), rs.getString("correo"), rs.getString("estado") };
            modelo.addRow(fila);
        }
        TableAdmin.setModel(modelo);
        rs.close(); ps.close(); con.close();
    } catch (Exception e) { System.out.println(e.getMessage()); }
}
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminAdmin().setVisible(true));
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarButton;
    private javax.swing.JButton EliminarButton;
    private javax.swing.JButton RegresaeButton;
    private javax.swing.JTable TableAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
