/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sistema_vacantes_java.administrador;

import com.mycompany.sistema_vacantes_java.conexion.ConexionBD;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Yaelita
 */
public class VacantesAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VacantesAdmin.class.getName());

    /**
     * Creates new form VacantesAdmin
     */
    public VacantesAdmin() {
        initComponents();
         this.pack();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        cargarCategorias();
        cargarVacantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(102, 102, 255)));

        jLabel1.setText("Gestion de Vacantes");

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setText("+ Nueva Vacante");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel2.setText("Lista de Vacantes");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas las vacantes" }));
        jComboBox1.addActionListener(this::jComboBox1ActionPerformed);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas las categorias" }));

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        jButton2.setText("Buscar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setText("Regresar");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(318, 318, 318)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       cargarVacantes();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
    InicioAdmin inicio = new InicioAdmin();

    inicio.setVisible(true);
    this.dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cargarVacantes();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    javax.swing.JTextField campoTrabajo = new javax.swing.JTextField();
    javax.swing.JTextField campoCategoria = new javax.swing.JTextField();
    javax.swing.JTextField campoSalario = new javax.swing.JTextField();
    javax.swing.JComboBox<String> campoEstado = new javax.swing.JComboBox<>(new String[]{"Activo", "Inactivo"});

    Object[] mensaje = {
        "Puesto de trabajo:", campoTrabajo,
        "Categoria:", campoCategoria,
        "Salario:", campoSalario,
        "Estado:", campoEstado
    };

    int opcion = JOptionPane.showConfirmDialog(this, mensaje, "Nueva Vacante", JOptionPane.OK_CANCEL_OPTION);
    if (opcion != JOptionPane.OK_OPTION) return;

    String trabajo = campoTrabajo.getText().trim();
    String categoria = campoCategoria.getText().trim();
    String salarioTexto = campoSalario.getText().trim();
    String estado = campoEstado.getSelectedItem().toString();

    if (trabajo.isEmpty() || categoria.isEmpty() || salarioTexto.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, rellene todos los campos.", "Campos Incompletos", JOptionPane.WARNING_MESSAGE);
        return;
    }

    double salario;
    try {
        salario = Double.parseDouble(salarioTexto);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El salario debe ser un número válido.", "Error de Validación", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        Connection con = ConexionBD.conectar();
        String sql = "INSERT INTO vacantes (trabajo, categoria, salario, estado) VALUES (?, ?, ?, ?)";
        PreparedStatement ps = con.prepareStatement(sql);
        ps.setString(1, trabajo);
        ps.setString(2, categoria);
        ps.setDouble(3, salario);
        ps.setString(4, estado);
        ps.executeUpdate();
        ps.close();
        con.close();

        JOptionPane.showMessageDialog(this, "Vacante registrada con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        cargarCategorias();
        cargarVacantes();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "No se pudo registrar la vacante.\n" + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void cargarCategorias() {
    jComboBox2.removeAllItems();
    jComboBox2.addItem("Todas las categorias");
    try {
        Connection con = ConexionBD.conectar();
        String sql = "SELECT DISTINCT categoria FROM vacantes WHERE categoria IS NOT NULL ORDER BY categoria";
        PreparedStatement ps = con.prepareStatement(sql);
        ResultSet rs = ps.executeQuery();
        while (rs.next()) { jComboBox2.addItem(rs.getString("categoria")); }
        rs.close(); ps.close(); con.close();
    } catch (Exception e) { System.out.println(e.getMessage()); }
}

  private void cargarVacantes() {
    String estadoFiltro = jComboBox1.getSelectedItem() != null ? jComboBox1.getSelectedItem().toString() : "Todas las vacantes";
    String categoriaFiltro = jComboBox2.getSelectedItem() != null ? jComboBox2.getSelectedItem().toString() : "Todas las categorias";
    String texto = jTextField1.getText().trim();

    DefaultTableModel modelo = new DefaultTableModel();
    modelo.addColumn("ID");
    modelo.addColumn("Trabajo");
    modelo.addColumn("Categoria");
    modelo.addColumn("Salario");
    modelo.addColumn("Estado");

    StringBuilder sql = new StringBuilder("SELECT * FROM vacantes WHERE 1=1");
    if (!estadoFiltro.equals("Todas las vacantes")) sql.append(" AND estado = ?");
    if (!categoriaFiltro.equals("Todas las categorias")) sql.append(" AND categoria = ?");
    if (!texto.isEmpty()) sql.append(" AND trabajo LIKE ?");

    try {
        Connection con = ConexionBD.conectar();
        PreparedStatement ps = con.prepareStatement(sql.toString());
        int indice = 1;
        if (!estadoFiltro.equals("Todas las vacantes")) ps.setString(indice++, estadoFiltro);
        if (!categoriaFiltro.equals("Todas las categorias")) ps.setString(indice++, categoriaFiltro);
        if (!texto.isEmpty()) ps.setString(indice++, "%" + texto + "%");

        ResultSet rs = ps.executeQuery();
        while (rs.next()) {
            Object fila[] = { rs.getInt("id"), rs.getString("trabajo"), rs.getString("categoria"), rs.getDouble("salario"), rs.getString("estado") };
            modelo.addRow(fila);
        }
        jTable2.setModel(modelo);
        rs.close(); ps.close(); con.close();
    } catch (Exception e) { System.out.println(e.getMessage()); }
}
    
    
    
    
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VacantesAdmin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
